### PR TITLE
PLAT-76466: Update samples to pull 2.x branch

### PR DESCRIPTION
**Pull request by sugardave**
Update dependencies from `next` to `^2.0.0`

Enact-DCO-1.0-Signed-off-by: Dave Freeman dave.freeman@lge.com

### CODE REVIEW

**Comment by ryanjduffy** [comment]
Not sure why Travis is failing. `enact-all-samples` builds locally fine for me. @JayCanuck or @webOS101 - any guesses on the issue?

**Comment by webOS101** [comment]
It's just what it says:  `Module not found: Error: Can't resolve 'query-string'`.  Didn't get addd to `enact-all-samples` and I missed that when it was updated. I'll push a fix for it.

**Comment by ryanjduffy** [comment]
I didn't realize we needed to add dependencies from the samples into "all-samples" too.

**Comment by webOS101** [comment]
💚

**Pull request merged**
