### PR TITLE
WRP-3073: Updated package dependencies to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by stanca-pop-lgp**
Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Updated package dependencies to fix security vulnerabilities.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-3073

### CODE REVIEW

**Review by daniel-stoian-lgp — APPROVED** [review]
LGTM

**Comment by hong6316** [comment]
I'm on verifying.
http://gecko.lge.com/jenkins/view/z-Enact/job/enact-samples-zip/3018/
http://gecko.lge.com/jenkins/view/z-Enact/job/enact-samples-zip/3019/
http://gecko.lge.com/jenkins/view/z-Enact/job/enact-samples-zip/3020/
http://gecko.lge.com/jenkins/view/z-Enact/job/enact-samples-zip/3021/

Please test these jenkins jobs next time, before PR. @stanca-pop-lgp @daniel-stoian-lgp

**Comment by daniel-stoian-lgp** [comment]
> I'm on verifying. http://gecko.lge.com/jenkins/view/z-Enact/job/enact-samples-zip/3018/ http://gecko.lge.com/jenkins/view/z-Enact/job/enact-samples-zip/3019/ http://gecko.lge.com/jenkins/view/z-Enact/job/enact-samples-zip/3020/ http://gecko.lge.com/jenkins/view/z-Enact/job/enact-samples-zip/3021/
> 
> Please test these jenkins jobs next time, before PR. @stanca-pop-lgp @daniel-stoian-lgp

Alright. I added this info in the guide you sent us

**Review by hong6316 — APPROVED** [review]
LGTM

**Pull request merged**
